directories:
  output: release
  buildResources: build
appId: com.haris.excel-saga
productName: ExcelSaga
files:
  - filter:
      - dist
      - main.cjs
      - package.json
win:
  target: nsis
electronVersion: 37.2.5
